Migrated into here
payfunc/model-log pull request #1
Opened 2021-02-26 16:13 UTC by florianebmeier

2021-02-26 16:56 UTC, robinnedergard requested changes
Match optionality of typeguard and properties for merchant and agent properties

2021-02-26 16:56 UTC, robinnedergard commented on Log/index.ts
> +			authly.Identifier.is(value.agent) &&
Is agent optional or not?

2021-02-26 16:56 UTC, robinnedergard commented on Log/index.ts
> +			(value.merchant == undefined || authly.Identifier.is(value.merchant)) &&
Maybe swapped merchant with agent as shard key?

2021-02-26 17:00 UTC, robinnedergard approved these changes

2021-03-02 12:14 UTC, nilssonemma approved these changes

2021-03-08 12:45 UTC, simonmika approved these changes

2021-03-08 12:45 UTC, merged